# Generated by Django 6.0.1 on 2026-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="voter_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
